/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mssql.CommandOperation;

/**
 *
 * @author Asus
 */
public class RegistrationPane extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationPane
     */
    
    CommandOperation cOP = new CommandOperation();
    public RegistrationPane() {
        initComponents();
    }
    
    public void register() {
        reg_eid.grabFocus();
    }
    public void addEventBackLogin(ActionListener event) {
        reg_loginBtn.addActionListener(event);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        reg_eid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        reg_uid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        reg_pass1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        reg_pass2 = new javax.swing.JPasswordField();
        reg_submitBtn = new javax.swing.JButton();
        reg_loginBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        reg_nid = new javax.swing.JTextField();

        setBackground(new java.awt.Color(252, 233, 192));

        jLabel1.setFont(new java.awt.Font("Rockwell", 3, 36)); // NOI18N
        jLabel1.setText("Restora RMS");

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 36)); // NOI18N
        jLabel2.setText("New Employee Registration");

        jLabel5.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel5.setText("NID : ");

        reg_eid.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        reg_eid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_eidActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel3.setText("User ID : ");

        reg_uid.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        reg_uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_uidActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel4.setText("Password : ");

        reg_pass1.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel6.setText("Retype Password : ");

        reg_pass2.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        reg_submitBtn.setBackground(new java.awt.Color(153, 255, 153));
        reg_submitBtn.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        reg_submitBtn.setText("Submit");
        reg_submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_submitBtnActionPerformed(evt);
            }
        });

        reg_loginBtn.setBackground(new java.awt.Color(153, 153, 255));
        reg_loginBtn.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        reg_loginBtn.setText("Back to Login");
        reg_loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_loginBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        jLabel7.setText("Employee ID : ");

        reg_nid.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        reg_nid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_nidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reg_submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(reg_uid, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(reg_pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(reg_eid, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(reg_nid, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(reg_pass2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(49, 49, 49)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(reg_loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addGap(417, 417, 417)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reg_loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(reg_eid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(reg_nid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(reg_uid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(reg_pass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(reg_pass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reg_submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reg_eidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_eidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_eidActionPerformed

    private void reg_uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_uidActionPerformed

    private void reg_nidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_nidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_nidActionPerformed

    private void reg_submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_submitBtnActionPerformed
        // TODO add your handling code here:
        String eid = reg_eid.getText();
        String nid = reg_nid.getText();
        String uid = reg_uid.getText();
        String pass1 = reg_pass1.getText();
        String pass2 = reg_pass2.getText();
        
        if(eid.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Employee ID cannot be empty");
        }
        else if(nid.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"NID cannot be empty");
        }
        else if(uid.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"User ID cannot be empty");
        }
        else if(pass1.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Password cannot be empty");
        }
        else if(pass2.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please re-type password");
        }
        else if(!pass1.equals(pass2))
        {
            JOptionPane.showMessageDialog(null,"Password didn't match");
        }
        else
        {
            try {
                cOP.Reg(eid, nid, uid, pass1);
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(RegistrationPane.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(RegistrationPane.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(RegistrationPane.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_reg_submitBtnActionPerformed

    private void reg_loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_loginBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reg_loginBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField reg_eid;
    private javax.swing.JButton reg_loginBtn;
    private javax.swing.JTextField reg_nid;
    private javax.swing.JPasswordField reg_pass1;
    private javax.swing.JPasswordField reg_pass2;
    private javax.swing.JButton reg_submitBtn;
    private javax.swing.JTextField reg_uid;
    // End of variables declaration//GEN-END:variables
}
