/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Owner;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import mssql.DBConnect;

/**
 *
 * @author Asus
 */
public class OwnerEmpPan extends javax.swing.JPanel {

    /**
     * Creates new form OwnerEmpPan
     */
    DBConnect dbc;
    ResultSet rs;
    
    public OwnerEmpPan() {
        initComponents();
        showTable();
        cons();
        
    }
    
    public void cons()
    {
        AddEmployee ae = new AddEmployee();
        UpdateEmp ue = new UpdateEmp();
        DeleteEmployee de = new DeleteEmployee();
        panelSlide1.setAnimate(1000);
        panelSlide1.init(ae, ue, de);
        
        this.addEventAdd(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                //  Show register form
                panelSlide1.show(0);
                
            }
        });
        
        addEventUpdate(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                //  Show register form
                panelSlide1.show(1);
                
            }
        });

        addEventDelete(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                //  Show register form
                panelSlide1.show(2);
                
            }
        });

        


        
    }
    
    public void addEventBack(ActionListener event){
        backBtn.addActionListener(event);
    }
    
    public void addEventAdd(ActionListener event) {
        addEmp.addActionListener(event);
    }
    
    public void addEventUpdate(ActionListener event) {
        upEmp.addActionListener(event);
    }

    public void addEventDelete(ActionListener event) {
        delEmp.addActionListener(event);
    }

        
    public void showTable()
    {
        try{
            dbc = new DBConnect();
            dbc.connectToDB();
            DefaultTableModel model = (DefaultTableModel) Table.getModel();
            model.setRowCount(0);
            rs = dbc.queryToDB("select * from Employee");
            
            while(rs.next())
            {
                String eid = String.valueOf(rs.getInt("employee_id"));
                String name = rs.getString("name");
                String nid = rs.getString("nid");
                String deg = rs.getString("designation");
                //String shift = rs.getString("Shift");
                String mblNo = rs.getString("mobile");
                String pa = rs.getString("address_");
                String salary = String.valueOf(rs.getInt("salary"));
                //String vs = rs.getString("Vaccine_Status");
                //String ec = rs.getString("EmergencyContact");
                
                String TableData[] = {eid,name,nid,deg,mblNo,pa,salary,};
                DefaultTableModel Tmodel = (DefaultTableModel) Table.getModel();
                Tmodel.addRow(TableData);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        upEmp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        addEmp = new javax.swing.JButton();
        delEmp = new javax.swing.JButton();
        panelBorder1 = new swing.PanelBorder();
        panelSlide1 = new swing.PanelSlide();
        empRefBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(252, 233, 192));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Back.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        upEmp.setBackground(new java.awt.Color(153, 255, 255));
        upEmp.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        upEmp.setText("Update Info");

        Table.setBackground(new java.awt.Color(204, 255, 204));
        Table.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Name", "NID", "Designation", "Mobile No.", "Present Address", "Salary"
            }
        ));
        Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Table);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(0).setPreferredWidth(35);
            Table.getColumnModel().getColumn(6).setPreferredWidth(30);
        }
        JTableHeader th = Table.getTableHeader();
        th.setFont(new java.awt.Font("Californian FB", Font.BOLD, 18));

        addEmp.setBackground(new java.awt.Color(153, 204, 255));
        addEmp.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        addEmp.setText("Add Employee");
        addEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpActionPerformed(evt);
            }
        });

        delEmp.setBackground(new java.awt.Color(255, 102, 102));
        delEmp.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        delEmp.setText("Delete Info");

        panelSlide1.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout panelSlide1Layout = new javax.swing.GroupLayout(panelSlide1);
        panelSlide1.setLayout(panelSlide1Layout);
        panelSlide1Layout.setHorizontalGroup(
            panelSlide1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        panelSlide1Layout.setVerticalGroup(
            panelSlide1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        panelBorder1.add(panelSlide1);
        panelSlide1.setBounds(0, 0, 1280, 300);

        empRefBtn.setBackground(new java.awt.Color(204, 255, 204));
        empRefBtn.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        empRefBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        empRefBtn.setText("Refresh");
        empRefBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empRefBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1570, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(delEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addEmp)))
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(empRefBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(54, 54, 54)
                        .addComponent(addEmp)
                        .addGap(23, 23, 23)
                        .addComponent(upEmp)
                        .addGap(26, 26, 26)
                        .addComponent(delEmp)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(empRefBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void addEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addEmpActionPerformed

    private void empRefBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empRefBtnActionPerformed
        // TODO add your handling code here:
        
        showTable();
    }//GEN-LAST:event_empRefBtnActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton addEmp;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton delEmp;
    private javax.swing.JButton empRefBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private swing.PanelBorder panelBorder1;
    private swing.PanelSlide panelSlide1;
    private javax.swing.JButton upEmp;
    // End of variables declaration//GEN-END:variables
}

