/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Owner;

import UserInterface.Main;
import java.awt.Window;
import java.awt.event.ActionListener;
import javax.swing.SwingUtilities;

/**
 *
 * @author Asus
 */
public class OwnerMainPan extends javax.swing.JPanel {

    /**
     * Creates new form OwnerMainPan
     */
    public OwnerMainPan() {
        initComponents();
    }
    
    public void addEventEmployee(ActionListener event){
        ownEmp.addActionListener(event);
    }
    
    public void addEventCoupon(ActionListener event){
        ownCoupon.addActionListener(event);
    }

    
    public void addEventCustomer(ActionListener event){
        ownCoupon.addActionListener(event);
    }
    
    public void addEventInventory(ActionListener event){
        ownInven.addActionListener(event);
    }
    
    public void addEventTransaction(ActionListener event){
        ownTransec.addActionListener(event);
    }
    
    public void addEventMenu(ActionListener event){
        ownMenu.addActionListener(event);
    }

    public void addEventInvoice(ActionListener event){
        ownInv.addActionListener(event);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ownEmp = new javax.swing.JButton();
        ownInv = new javax.swing.JButton();
        ownCoupon = new javax.swing.JButton();
        ownInven = new javax.swing.JButton();
        ownTransec = new javax.swing.JButton();
        ownMenu = new javax.swing.JButton();
        ownLogOut = new javax.swing.JButton();

        setBackground(new java.awt.Color(252, 233, 192));

        ownEmp.setBackground(new java.awt.Color(153, 153, 255));
        ownEmp.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        ownEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/employee-icon50.png"))); // NOI18N
        ownEmp.setText("   Employee");
        ownEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownEmpActionPerformed(evt);
            }
        });

        ownInv.setBackground(new java.awt.Color(255, 153, 204));
        ownInv.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        ownInv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/invoice_50.png"))); // NOI18N
        ownInv.setText(" Invoice               ");

        ownCoupon.setBackground(new java.awt.Color(255, 204, 204));
        ownCoupon.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        ownCoupon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/coupon.png"))); // NOI18N
        ownCoupon.setText("      Coupon");
        ownCoupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownCouponActionPerformed(evt);
            }
        });

        ownInven.setBackground(new java.awt.Color(153, 255, 153));
        ownInven.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        ownInven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/inventory_50.png"))); // NOI18N
        ownInven.setText("   Inventory");

        ownTransec.setBackground(new java.awt.Color(255, 102, 102));
        ownTransec.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        ownTransec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transaction-icon-50.png"))); // NOI18N
        ownTransec.setText("  Transaction       ");

        ownMenu.setBackground(new java.awt.Color(153, 255, 153));
        ownMenu.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        ownMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu_50.png"))); // NOI18N
        ownMenu.setText("   Menu        ");

        ownLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/log_out_642.png"))); // NOI18N
        ownLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ownEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                    .addComponent(ownCoupon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ownInven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(424, 424, 424)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ownInv, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ownTransec, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ownMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ownLogOut)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownEmp)
                    .addComponent(ownInv))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownCoupon)
                    .addComponent(ownMenu))
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownInven)
                    .addComponent(ownTransec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                .addComponent(ownLogOut)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ownEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownEmpActionPerformed
        // TODO add your handling code here:
        //OwnerEmpPan oep = new OwnerEmpPan();
        //setVisible(false);
        //oep.show();
        
    }//GEN-LAST:event_ownEmpActionPerformed

    private void ownLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownLogOutActionPerformed
        // TODO add your handling code here:
        //dispose();
        //Main mn = new Main();
        //mn.setVisible(true);
        Window wn = SwingUtilities.getWindowAncestor(this);
        wn.dispose();
        Main mn = new Main();
        mn.setVisible(true);

    }//GEN-LAST:event_ownLogOutActionPerformed

    private void ownCouponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownCouponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownCouponActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ownCoupon;
    private javax.swing.JButton ownEmp;
    private javax.swing.JButton ownInv;
    private javax.swing.JButton ownInven;
    private javax.swing.JButton ownLogOut;
    private javax.swing.JButton ownMenu;
    private javax.swing.JButton ownTransec;
    // End of variables declaration//GEN-END:variables
}
