/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Owner;

import UserInterface.Main;
import java.awt.Window;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import mssql.DBConnect;

/**
 *
 * @author Asus
 */
public class OwnerCouponPan extends javax.swing.JPanel {

    /**
     * Creates new form OwnerMenuPan
     */
    DBConnect dbc;
    ResultSet rs;
    String iid;
    
    public OwnerCouponPan() {
        initComponents();
        showMenuTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        addCode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addPer = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        MenuTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        searchBox = new javax.swing.JTextField();
        searchItem = new javax.swing.JButton();
        ownLogOut = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        addMax = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addExpiry = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        upExpiry = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        upMax = new javax.swing.JTextField();
        upCode = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        upPer = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        delCode = new javax.swing.JLabel();
        delPer = new javax.swing.JLabel();
        delMax = new javax.swing.JLabel();
        delExpiry = new javax.swing.JLabel();

        setBackground(new java.awt.Color(252, 233, 192));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Back.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel5.setText("Coupon code : ");

        addCode.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel6.setText("Percentage : ");

        addPer.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        addBtn.setBackground(new java.awt.Color(102, 153, 255));
        addBtn.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        MenuTable.setBackground(new java.awt.Color(255, 255, 204));
        MenuTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MenuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coupon ID", "Coupon Code", "Percentage", "Max Amount", "Expiry Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(MenuTable);

        jLabel4.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel4.setText("Coopon Code : ");

        searchBox.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        searchItem.setBackground(new java.awt.Color(204, 255, 255));
        searchItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        searchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemActionPerformed(evt);
            }
        });

        ownLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/log_out_642.png"))); // NOI18N
        ownLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownLogOutActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel11.setText("Max Amount : ");

        addMax.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel2.setText("Expiry date : ");

        jLabel3.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel3.setText("Expiry date : ");

        jLabel12.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel12.setText("Max Amount : ");

        jLabel13.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel13.setText("Coupon code : ");

        upMax.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        upCode.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel14.setText("Percentage : ");

        upPer.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        updateBtn.setBackground(new java.awt.Color(153, 255, 255));
        updateBtn.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel7.setText("Expiry date : ");

        jLabel15.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel15.setText("Max Amount : ");

        jLabel16.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel16.setText("Coupon code : ");

        jLabel17.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel17.setText("Percentage : ");

        deleteBtn.setBackground(new java.awt.Color(255, 102, 102));
        deleteBtn.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        delCode.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        delCode.setText("null");

        delPer.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        delPer.setText("null");

        delMax.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        delMax.setText("null");

        delExpiry.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        delExpiry.setText("null");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(488, 488, 488)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ownLogOut))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(419, 419, 419)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(searchItem))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addCode, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(addMax, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(addPer, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(addBtn)
                                .addGap(21, 21, 21)))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(upCode, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(upMax, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(upPer, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(upExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(updateBtn)
                                .addGap(21, 21, 21)))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel15))
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(delPer, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                                    .addComponent(delMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(16, 16, 16))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(delExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(delCode, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(309, 309, 309)
                                .addComponent(deleteBtn)))
                        .addGap(255, 255, 255)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(searchItem, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addCode))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addPer))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addMax))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(upCode))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(upPer))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(upMax))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(upExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateBtn)))
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delCode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delPer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delMax, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delExpiry, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ownLogOut)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed
    
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String add_code = addCode.getText();
        float add_per = Float.valueOf(addPer.getText());
        int add_max = Integer.valueOf(addMax.getText());
        long millis = addExpiry.getDate().getTime();
        String add_expiry = new java.sql.Date(millis).toString();
        
        if(add_code.isEmpty() || add_expiry.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "All fields are required!");
        }
        
        else{
            try{
                dbc = new DBConnect();
                dbc.connectToDB();
                boolean qr = dbc.ToDB("insert into Coupon"
                                       +" values ('"+add_code+"',"+add_per+", '"+add_expiry+"', "+add_max+")");

                if(qr)
                {
                    JOptionPane.showMessageDialog(null, "Coupon Added Successfully");
                    showMenuTable();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Error adding coupon");
                }
            }catch(Exception e){

            }
        }

        
    }//GEN-LAST:event_addBtnActionPerformed

    private void searchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemActionPerformed
        // TODO add your handling code here:

        iid = searchBox.getText();
        try{
            dbc = new DBConnect();
            dbc.connectToDB();

            if( !iid.isEmpty())
            {
                rs = dbc.queryToDB("select top 1 * from Coupon where code like '%"+iid+"%'");
            }
           
            else
            {
                JOptionPane.showMessageDialog(null, "Please enter code");
            }
            
            if(!rs.next())
            {
                JOptionPane.showMessageDialog(null, "No coupon code found!");
                delCode.setText("");
                delPer.setText("");
                delExpiry.setText("");
                delMax.setText("");
                upCode.setText("");
                upPer.setText("");
                //upExpiry.setText("");
                upMax.setText("");
            }
            else
            {
                String up_code = rs.getString("code");
                float up_per = rs.getFloat("percentage");
                String up_date = String.valueOf(rs.getDate("validity"));
                int max = rs.getInt("max_amount");
                
                upCode.setText(up_code);
                upPer.setText(String.valueOf(up_per));
                upExpiry.setDate(java.sql.Date.valueOf(up_date));
                upMax.setText(String.valueOf(max));
                
                delCode.setText(up_code);
                delPer.setText(String.valueOf(up_per));
                delExpiry.setText(up_date);
                delMax.setText(String.valueOf(max));

            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_searchItemActionPerformed

    private void ownLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownLogOutActionPerformed
        // TODO add your handling code here:
        //dispose();
        //Main mn = new Main();
        //mn.setVisible(true);
        Window wn = SwingUtilities.getWindowAncestor(this);
        wn.dispose();
        Main mn = new Main();
        mn.setVisible(true);
    }//GEN-LAST:event_ownLogOutActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        try{
            dbc = new DBConnect();
            dbc.connectToDB();
            boolean qr = dbc.ToDB("delete from Coupon where coupon_id = (select top 1 coupon_id from Coupon where code like '%"+iid+"%')");
            
            if(qr)
            {
                JOptionPane.showMessageDialog(null, "Coupon deleted successfully");
            }
            else{
                JOptionPane.showMessageDialog(null, "Error deleting successfully");
            }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
        }
        
        delCode.setText("");
        delPer.setText("");
        delExpiry.setText("");
        delMax.setText("");
        
    }//GEN-LAST:event_deleteBtnActionPerformed
    
    public void showMenuTable()
    {
        try{
            dbc = new DBConnect();
            dbc.connectToDB();
            DefaultTableModel model = (DefaultTableModel) MenuTable.getModel();
            model.setRowCount(0);
            rs = dbc.queryToDB("select * from Coupon");
            
            while(rs.next())
            {
                String up_id = String.valueOf(rs.getInt("coupon_id"));
                String up_code = rs.getString("code");
                String up_per = String.valueOf(rs.getFloat("percentage"));
                String up_date = String.valueOf(rs.getDate("validity"));
                String max = String.valueOf(rs.getInt("max_amount"));

                String TableData[] = {up_id, up_code, up_per, max, up_date};
                DefaultTableModel Tmodel = (DefaultTableModel) MenuTable.getModel();
                Tmodel.addRow(TableData);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
    }
    
    public void addEventBack(ActionListener event){
        backBtn.addActionListener(event);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MenuTable;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField addCode;
    private com.toedter.calendar.JDateChooser addExpiry;
    private javax.swing.JTextField addMax;
    private javax.swing.JTextField addPer;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel delCode;
    private javax.swing.JLabel delExpiry;
    private javax.swing.JLabel delMax;
    private javax.swing.JLabel delPer;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton ownLogOut;
    private javax.swing.JTextField searchBox;
    private javax.swing.JButton searchItem;
    private javax.swing.JTextField upCode;
    private com.toedter.calendar.JDateChooser upExpiry;
    private javax.swing.JTextField upMax;
    private javax.swing.JTextField upPer;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
