/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Receptionist;

import Owner.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mssql.DBConnect;

/**
 *
 * @author Asus
 */
public class CustomerPan extends javax.swing.JPanel {

    /**
     * Creates new form OwnerCusPan
     */
    
    DBConnect dbc;
    ResultSet rs, rs2;
    
    public CustomerPan() {
        initComponents();
        cons();
        showTable();
        
    }
    
    public void cons()
    {
        AddCustomer addC = new AddCustomer();
        UpdateCus upC = new UpdateCus();
        DeleteCustomer delC = new DeleteCustomer();
        
        panelSlide1.setAnimate(1000);
        panelSlide1.init(addC, upC, delC);
        
        addEventAdd(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                //  Show register form
                panelSlide1.show(0);
                
            }
        });
        
        addEventUpdate(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                //  Show register form
                panelSlide1.show(1);
                
            }
        });

        addEventDelete(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                //  Show register form
                panelSlide1.show(2);
                
            }
        });
    }
    
     public void showTable()
    {
        try{
            dbc = new DBConnect();
            dbc.connectToDB();
            DefaultTableModel model = (DefaultTableModel) Table.getModel();
            model.setRowCount(0);
            rs = dbc.queryToDB("select Customer.customer_id, Customer.name, Customer.mobile, Customer.email, CustomerPoints.points, CustomerPoints.expiry "
                                +" from Customer left join CustomerPoints"
                                +" on Customer.customer_id  =CustomerPoints.customer_id");
            //rs2 = dbc.queryToDB("select * from CustomerPoints");
            
            while(rs.next())
            {
                String cid = String.valueOf(rs.getInt("customer_id"));
                String points = String.valueOf(rs.getInt("points"));
                String name = rs.getString("name");
                String mbl = rs.getString("mobile");
                String vs = rs.getString("email");
                String ex = rs.getString("expiry");

                
                String TableData[] = {cid,name,mbl,vs,points,ex};
                DefaultTableModel Tmodel = (DefaultTableModel) Table.getModel();
                Tmodel.addRow(TableData);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        addCustomer = new javax.swing.JButton();
        upCustomer = new javax.swing.JButton();
        delCustomer = new javax.swing.JButton();
        cusRefBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        panelBorder1 = new swing.PanelBorder();
        panelSlide1 = new swing.PanelSlide();

        setBackground(new java.awt.Color(252, 233, 192));
        setMaximumSize(new java.awt.Dimension(1570, 900));
        setMinimumSize(new java.awt.Dimension(1570, 900));
        setPreferredSize(new java.awt.Dimension(1570, 900));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Back.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        addCustomer.setBackground(new java.awt.Color(102, 153, 255));
        addCustomer.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        addCustomer.setText("Add Customer");
        addCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerActionPerformed(evt);
            }
        });

        upCustomer.setBackground(new java.awt.Color(153, 255, 255));
        upCustomer.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        upCustomer.setText("Update Info");

        delCustomer.setBackground(new java.awt.Color(255, 102, 102));
        delCustomer.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        delCustomer.setText("Delete Info");

        cusRefBtn.setBackground(new java.awt.Color(204, 255, 204));
        cusRefBtn.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        cusRefBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        cusRefBtn.setText("Refresh");
        cusRefBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusRefBtnActionPerformed(evt);
            }
        });

        Table.setBackground(new java.awt.Color(204, 255, 255));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Name", "Mobile", "Email", "Points", "Expiry Date"
            }
        ));
        jScrollPane2.setViewportView(Table);

        panelSlide1.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout panelSlide1Layout = new javax.swing.GroupLayout(panelSlide1);
        panelSlide1.setLayout(panelSlide1Layout);
        panelSlide1Layout.setHorizontalGroup(
            panelSlide1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1220, Short.MAX_VALUE)
        );
        panelSlide1Layout.setVerticalGroup(
            panelSlide1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        panelBorder1.add(panelSlide1);
        panelSlide1.setBounds(0, 0, 1220, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(1413, Short.MAX_VALUE)
                .addComponent(cusRefBtn)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(delCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCustomer))))
                .addGap(50, 50, 50)
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(27, 27, 27)
                        .addComponent(addCustomer)
                        .addGap(23, 23, 23)
                        .addComponent(upCustomer)
                        .addGap(26, 26, 26)
                        .addComponent(delCustomer))
                    .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cusRefBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void addEventBack(ActionListener event){
        backBtn.addActionListener(event);
    }
    
    public void addEventAdd(ActionListener event) {
        addCustomer.addActionListener(event);
    }
    
    public void addEventUpdate(ActionListener event) {
        upCustomer.addActionListener(event);
    }

    public void addEventDelete(ActionListener event) {
        delCustomer.addActionListener(event);
    }
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void addCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCustomerActionPerformed

    private void cusRefBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusRefBtnActionPerformed
        // TODO add your handling code here:
        showTable();
    }//GEN-LAST:event_cusRefBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton addCustomer;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton cusRefBtn;
    private javax.swing.JButton delCustomer;
    private javax.swing.JScrollPane jScrollPane2;
    private swing.PanelBorder panelBorder1;
    private swing.PanelSlide panelSlide1;
    private javax.swing.JButton upCustomer;
    // End of variables declaration//GEN-END:variables
}
