/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Receptionist;

import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mssql.DBConnect;

/**
 *
 * @author Asus
 */
public class InvoicePan extends javax.swing.JPanel {

    /**
     * Creates new form InvoicePan
     */
    private static final SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss");
    private static final SimpleDateFormat sdf3 = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

    DBConnect dbc;
    ResultSet rs, rs2;
    String cid, mob;
    String items, cusPoint, waiterId, expDate;
    double value_=0;
    double subTotal = 0;
    double coupDisc = 0;
    double pointDisc =0;
    double vat, Discount, total;
    double per=0; 
    int max=0;
    int inP = 0;
    int currentEmp;
    public InvoicePan() {
        initComponents();
        showMenuTable();
    }
    
    public InvoicePan(int currentEmp) {
        this.currentEmp = currentEmp;
        initComponents();
        showMenuTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtnRes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        deleteCID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        deleteMobile = new javax.swing.JTextField();
        searchEID = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        points = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        vs = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MenuTable = new javax.swing.JTable();
        waiter = new javax.swing.JLabel();
        getBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nop = new javax.swing.JLabel();
        sel2 = new javax.swing.JLabel();
        sel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoiceTable = new javax.swing.JTable();
        sel4 = new javax.swing.JLabel();
        sel5 = new javax.swing.JLabel();
        sel7 = new javax.swing.JLabel();
        sel8 = new javax.swing.JLabel();
        sel9 = new javax.swing.JLabel();
        cNameLabel = new javax.swing.JLabel();
        cMobileLabel = new javax.swing.JLabel();
        serveLabel = new javax.swing.JLabel();
        subLabel = new javax.swing.JLabel();
        vatLabel = new javax.swing.JLabel();
        couDisLabel = new javax.swing.JLabel();
        poiDisLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        emni = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        couponJTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pointsJTF = new javax.swing.JTextField();
        applyBtn = new javax.swing.JButton();
        reedemBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        exp = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pm = new javax.swing.JComboBox<String>();
        om = new javax.swing.JComboBox<String>();
        cus = new javax.swing.JButton();

        setBackground(new java.awt.Color(252, 233, 192));
        setMaximumSize(new java.awt.Dimension(1570, 743));
        setMinimumSize(new java.awt.Dimension(1570, 743));

        backBtnRes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Back.png"))); // NOI18N
        backBtnRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnResActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel2.setText("Customer ID: ");

        deleteCID.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel4.setText("Mobile:");

        deleteMobile.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        searchEID.setBackground(new java.awt.Color(204, 255, 204));
        searchEID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        searchEID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEIDActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel1.setText("Name :");

        jLabel8.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel8.setText("Points : ");

        points.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        name.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        vs.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        MenuTable.setBackground(new java.awt.Color(204, 255, 255));
        MenuTable.setFont(new java.awt.Font("Californian FB", 0, 18)); // NOI18N
        MenuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Category", "Item Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(MenuTable);
        if (MenuTable.getColumnModel().getColumnCount() > 0) {
            MenuTable.getColumnModel().getColumn(0).setMinWidth(50);
            MenuTable.getColumnModel().getColumn(0).setMaxWidth(50);
            MenuTable.getColumnModel().getColumn(1).setMinWidth(100);
            MenuTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            MenuTable.getColumnModel().getColumn(1).setMaxWidth(100);
            MenuTable.getColumnModel().getColumn(3).setMinWidth(80);
            MenuTable.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        waiter.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        getBtn.setBackground(new java.awt.Color(102, 153, 255));
        getBtn.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        getBtn.setText("+Add");
        getBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(252, 233, 192));

        nop.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        nop.setText("Name : ");

        sel2.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        sel2.setText("Mobile : ");

        sel3.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        sel3.setText("Served by : ");

        invoiceTable.setBackground(new java.awt.Color(204, 255, 204));
        invoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Rate", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(invoiceTable);
        if (invoiceTable.getColumnModel().getColumnCount() > 0) {
            invoiceTable.getColumnModel().getColumn(1).setMinWidth(50);
            invoiceTable.getColumnModel().getColumn(1).setMaxWidth(50);
            invoiceTable.getColumnModel().getColumn(2).setMinWidth(100);
            invoiceTable.getColumnModel().getColumn(2).setMaxWidth(100);
            invoiceTable.getColumnModel().getColumn(3).setMinWidth(125);
            invoiceTable.getColumnModel().getColumn(3).setMaxWidth(125);
        }

        sel4.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        sel4.setText("VAT : ");

        sel5.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        sel5.setText("Sub total :");

        sel7.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        sel7.setText("Coupon Disc. :");

        sel8.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        sel8.setText("Points Disc. :");

        sel9.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        sel9.setText("Total :");

        cNameLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        cNameLabel.setText("null");

        cMobileLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        cMobileLabel.setText("null");

        serveLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        serveLabel.setText("null");

        subLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        subLabel.setText("0.0");

        vatLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        vatLabel.setText("0.0");

        couDisLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        couDisLabel.setText("0.0");

        poiDisLabel.setFont(new java.awt.Font("Californian FB", 1, 18)); // NOI18N
        poiDisLabel.setText("0.0");

        totalLabel.setFont(new java.awt.Font("Californian FB", 1, 20)); // NOI18N
        totalLabel.setText("0.0");

        saveBtn.setBackground(new java.awt.Color(255, 102, 0));
        saveBtn.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        saveBtn.setText("Proceed");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nop)
                                .addGap(18, 18, 18)
                                .addComponent(cNameLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cMobileLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(serveLabel)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sel4)
                            .addComponent(sel9)
                            .addComponent(sel8)
                            .addComponent(sel7)
                            .addComponent(sel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subLabel)
                            .addComponent(vatLabel)
                            .addComponent(couDisLabel)
                            .addComponent(poiDisLabel)
                            .addComponent(totalLabel))
                        .addGap(115, 115, 115))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cMobileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(couDisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(poiDisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn))
        );

        emni.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        emni.setText("selected");

        jLabel3.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel3.setText("Coupon :");

        couponJTF.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel5.setText("Points : ");

        pointsJTF.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        applyBtn.setBackground(new java.awt.Color(255, 102, 255));
        applyBtn.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        applyBtn.setText("Apply");
        applyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyBtnActionPerformed(evt);
            }
        });

        reedemBtn.setBackground(new java.awt.Color(153, 255, 153));
        reedemBtn.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        reedemBtn.setText("Reedem");
        reedemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reedemBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel9.setText("Expiry : ");

        exp.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel6.setText("Payment Method : ");

        jLabel7.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel7.setText("Order Type : ");

        pm.setBackground(new java.awt.Color(255, 255, 204));
        pm.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        pm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "bKash", "Nagad", "Rocket", "Visa", "MasterCard", "Cheque", "Other" }));

        om.setBackground(new java.awt.Color(255, 255, 204));
        om.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        om.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dine in", "Take away", "FoodPanda", "PathaoFood", "HungryNaki", "Other" }));

        cus.setBackground(new java.awt.Color(153, 153, 255));
        cus.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        cus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/customer_icon50.png"))); // NOI18N
        cus.setText("Customer");
        cus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtnRes, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cus, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(650, 650, 650)
                                .addComponent(vs, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteCID, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(searchEID))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(points, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(exp, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(getBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(couponJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pointsJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(applyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(reedemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pm, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(om, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waiter, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(365, 365, 365))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(469, 469, 469)
                    .addComponent(emni)
                    .addContainerGap(1042, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backBtnRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchEID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vs, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(getBtn)
                                .addGap(120, 120, 120)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(om, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(couponJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(applyBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pointsJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(reedemBtn))
                                .addGap(44, 44, 44))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(points, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(waiter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(197, 197, 197)
                    .addComponent(emni, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(511, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void addEventReservation(ActionListener event) {
        backBtnRes.addActionListener(event);
    }
    
    public void addEventCustomer(ActionListener event) {
        cus.addActionListener(event);
    }
    
    
    private void backBtnResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnResActionPerformed
    
    private void clear()
    {
        deleteCID.setText("");
        deleteMobile.setText("");

    }
    
    private void searchEIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEIDActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) invoiceTable.getModel();
        model.setRowCount(0);
        subTotal=0;
        vat = 0;
        
        cid = deleteCID.getText();
        mob = deleteMobile.getText();

        try{
            dbc = new DBConnect();
            dbc.connectToDB();

            if( !cid.isEmpty() )
            {
                rs = dbc.queryToDB("select top 1 * from Customer where customer_id = "+cid);
                rs2 = dbc.queryToDB("select top 1 points from CustomerPoints, expiry where customer_id="+cid);

            }
            else if( !mob.isEmpty() )
            {
                rs = dbc.queryToDB("select top 1 * from Customer where mobile = '"+mob+"'");
                rs2 = dbc.queryToDB("select top 1 points, expiry from CustomerPoints where customer_id=(select top 1 customer_id from Customer where mobile='"+mob+"')");                

            }
            else
            {
                JOptionPane.showMessageDialog(null, "Please enter Customer ID or Mobile");
            }

            if(!rs.next())
            {
                JOptionPane.showMessageDialog(null, "No customer found with provided information");
                deleteCID.setText("");
                deleteMobile.setText("");
            }
            else{
                if(!rs2.next())
                {
                    if(!cid.isEmpty())
                    {
                        boolean q = dbc.ToDB("insert into CustomerPoints values ("+cid+", 0, '2000-01-01')");
                    }
                    else
                    {
                        boolean q = dbc.ToDB("insert into CustomerPoints values ((select top 1 customer_id from Customer where mobile='"+mob+"'), 0, '2000-01-01')");
                    }
                }
                
                cid = String.valueOf(rs.getInt("customer_id"));                
                String Delname = rs.getString("name");
                String delMobile = rs.getString("mobile");
                expDate = String.valueOf(rs2.getDate("expiry"));
                cusPoint = String.valueOf(rs2.getInt("points"));
                //                System.out.println("Here I am******************************************************"+Delname+" "+expDate);

                name.setText(Delname);                
                points.setText(cusPoint);
                exp.setText(expDate);
                cNameLabel.setText(Delname);
                cMobileLabel.setText(delMobile);
                ResultSet rs3 = dbc.queryToDB("select top 1 name from Employee where employee_id="+currentEmp);
                rs3.next();
                String ce= rs3.getString("name");
                serveLabel.setText(ce);

            }
            
            

        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, "Ex");

        }
    }//GEN-LAST:event_searchEIDActionPerformed
    
    private void showSub()
    {
        subLabel.setText(String.valueOf(subTotal));
        vat = subTotal * 0.075;            
        coupDisc = subTotal * (per/100);
        if(coupDisc>max)
        {
            coupDisc = max;
        }
        vatLabel.setText(String.valueOf(vat));
        couDisLabel.setText(String.valueOf(coupDisc));
        poiDisLabel.setText(String.valueOf(pointDisc));
        total = subTotal + vat - coupDisc - pointDisc;
        totalLabel.setText(String.valueOf(total));
    }
    
    /*
    private void saveTransaction()
    {
        String invoiveId="";
        try{
                
            dbc = new DBConnect();
            dbc.connectToDB();

            rs = dbc.queryToDB("select top 1 invoice_id from Invoice where Customer_id= "+cid+" order by invoice_id DESC");

            while(rs.next())
            {
                invoiveId = String.valueOf(rs.getInt("invoice_id"));
            }
            
            if(!invoiveId.isEmpty())
            {
                boolean qr = dbc.ToDB("insert into Transactions (invoice_id, category, amount, date_)"
                +" values ("+invoiveId+", 'Dine In' ,"+Total+", GETDATE())");
                
                if(!qr)
                {
                    JOptionPane.showMessageDialog(null, "Error adding transaction");
                }
            }
            

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
    }*/
        
     public void showMenuTable()
    {
        try{
            dbc = new DBConnect();
            dbc.connectToDB();
            DefaultTableModel model = (DefaultTableModel) MenuTable.getModel();
            model.setRowCount(0);
            rs = dbc.queryToDB("select * from Menu");
            
            while(rs.next())
            {
                String itemId = String.valueOf(rs.getInt("item_id"));
                String cat = rs.getString("category");
                String itemName = rs.getString("item_name");
                String price = String.valueOf(rs.getInt("price"));

                String TableData[] = {itemId,cat,itemName,price};
                DefaultTableModel Tmodel = (DefaultTableModel) MenuTable.getModel();
                Tmodel.addRow(TableData);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
    }
    
    private void getBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBtnActionPerformed
        // TODO add your handling code here:
        if(MenuTable.getSelectedRow() == -1)
        {
            JOptionPane.showMessageDialog(null, "Please select an item first!");
        }
        else{
            int q = Integer.valueOf(JOptionPane.showInputDialog("Quantity: "));
            //nop.setText(MenuTable.getValueAt(MenuTable.getSelectedRow(), 0).toString()+" X "+q);
            String item = MenuTable.getValueAt(MenuTable.getSelectedRow(), 2).toString();
            String quan = String.valueOf(q);
            String rate = MenuTable.getValueAt(MenuTable.getSelectedRow(), 3).toString();
            value_ = Float.valueOf(rate) * q;
            String value = String.valueOf(value_);
            subTotal += value_;            
            
           
            String row[] = {item, quan, rate, value};
            DefaultTableModel model = (DefaultTableModel) invoiceTable.getModel();
            model.addRow(row);            
            showSub();
        }
                
    }//GEN-LAST:event_getBtnActionPerformed

    private void applyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyBtnActionPerformed
        // TODO add your handling code here:
        String coupon = couponJTF.getText();
        
        if(coupon.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter coupon code!");
        }
        else{
            try{
                dbc = new DBConnect();
                dbc.connectToDB();
                ResultSet rs = dbc.queryToDB("select * from Coupon where code = '"+coupon+"' and validity > GETDATE()");
                
                if(!rs.next())
                {
                    JOptionPane.showMessageDialog(null, "Coupon code is NOT valid!");
                    coupDisc = 0;
                }
                else
                {
                    per = rs.getDouble("percentage");
                    max = rs.getInt("max_amount");
                    JOptionPane.showMessageDialog(null, "Coupon added succesfully ");
                    showSub();
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);            
            }
        }
        
    }//GEN-LAST:event_applyBtnActionPerformed

    private void reedemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reedemBtnActionPerformed
        // TODO add your handling code here:
        if(points.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please select a customer first");
        }
        
        else
        {
            inP = Integer.valueOf(pointsJTF.getText());
        
            if(Integer.valueOf(cusPoint)<inP)
            {
                JOptionPane.showMessageDialog(null, "Not available points");
            }
            else if(java.sql.Date.valueOf(expDate).compareTo(java.sql.Date.valueOf(LocalDate.now())) > 0)
            {
                //thik ache
                pointDisc=(double) inP;
                //poiDisLabel.setText(String.valueOf(pointDisc));
                showSub();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Points expired!");
            }
        }
        
    }//GEN-LAST:event_reedemBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String pmm = String.valueOf(pm.getSelectedItem());
        String omm = String.valueOf(om.getSelectedItem());
        
        if(cid.isEmpty() || currentEmp==0)
        {
            JOptionPane.showMessageDialog(null, "Please select customer");
        }
        else
        {
            try{
                dbc = new DBConnect();
                dbc.connectToDB();
                boolean qr = dbc.ToDB("insert into Receipts"
                                       +" values ("+cid+","+currentEmp+","+total+", '"+pmm+"', '"+omm+"')");

                if(qr)
                {
                    Timestamp timestamp = new Timestamp(System.currentTimeMillis());
                    
                    try{
                        
                        File file = new File("C:\\Users\\jandr\\Desktop\\CSE3224\\Project\\RMS\\src\\Invoices\\"+sdf1.format(timestamp)+".txt");
                        System.out.println("here");
                        if (file.createNewFile()) {
                            System.out.println("File created: " + file.getName());
                        } else {
                            System.out.println("File already exists.");
                        }
                        System.out.println("now here");
                        PrintWriter os = new PrintWriter(file);
                        
                        os.println("\t*** Some Restaurant ***\n");
                        
                        os.println("Customer name : "+cNameLabel.getText());
                        os.println("Customer mobile : "+cMobileLabel.getText());
                        os.println("Served by : "+serveLabel.getText());
                        os.println("Order Type : "+omm);
                        os.println("Date and Time : "+sdf3.format(timestamp));                        
                        os.println("New Point Balance: ");
                        os.println("New Point Expiry Date: ");
                        os.println("\n\n");
                        os.println("------------------------------------------------------");
                        os.println("Item\t\t\tQuantity\tRate\t\tValue");
                        os.println("------------------------------------------------------");
                        
                        for (int row = 0; row < invoiceTable.getRowCount(); row++) {
                            for (int col = 0; col < invoiceTable.getColumnCount(); col++) {
                                os.print(invoiceTable.getValueAt(row, col));
                                if(col == 0)
                                {
                                    os.print("\t\t\t");
                                }
                                else if(col == 1)
                                {
                                    os.print("\t");
                                }
                                else if(col==2)
                                {
                                    os.print("\t\t");
                                }
                                
                            }
                            
                            os.println("\n");
                        }
                        os.println("------------------------------------------------------");
                        
                        os.println("\t\t\t\t\t\tSub total: "+subLabel.getText());
                        os.println("\t\t\t\t\t\tVAT: "+vatLabel.getText());
                        os.println("\t\t\t\t\t\tCoupon discount: "+couDisLabel.getText());
                        os.println("\t\t\t\t\t\tPoint discount: "+poiDisLabel.getText());
                        os.println("\t\t\t\t\t\tTotal: "+totalLabel.getText());
                        os.println("Payment Method : "+pmm);
                        
                        os.close();

                    }catch (IOException e) {
                        System.out.println("An error occurred.");
                        e.printStackTrace();
                    }

                    
                    JOptionPane.showMessageDialog(null, "Reciept saved!");
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Error! Reciept is NOT saved!");
                }
            }catch(Exception e){

            }
            
            
        }
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MenuTable;
    private javax.swing.JButton applyBtn;
    private javax.swing.JButton backBtnRes;
    private javax.swing.JLabel cMobileLabel;
    private javax.swing.JLabel cNameLabel;
    private javax.swing.JLabel couDisLabel;
    private javax.swing.JTextField couponJTF;
    private javax.swing.JButton cus;
    private javax.swing.JTextField deleteCID;
    private javax.swing.JTextField deleteMobile;
    private javax.swing.JLabel emni;
    private javax.swing.JLabel exp;
    private javax.swing.JButton getBtn;
    private javax.swing.JTable invoiceTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nop;
    private javax.swing.JComboBox<String> om;
    private javax.swing.JComboBox<String> pm;
    private javax.swing.JLabel poiDisLabel;
    private javax.swing.JLabel points;
    private javax.swing.JTextField pointsJTF;
    private javax.swing.JButton reedemBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchEID;
    private javax.swing.JLabel sel2;
    private javax.swing.JLabel sel3;
    private javax.swing.JLabel sel4;
    private javax.swing.JLabel sel5;
    private javax.swing.JLabel sel7;
    private javax.swing.JLabel sel8;
    private javax.swing.JLabel sel9;
    private javax.swing.JLabel serveLabel;
    private javax.swing.JLabel subLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel vatLabel;
    private javax.swing.JLabel vs;
    private javax.swing.JLabel waiter;
    // End of variables declaration//GEN-END:variables
}
