/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Receptionist;

import Owner.*;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import mssql.DBConnect;

/**
 *
 * @author Asus
 */
public class UpdateCus extends javax.swing.JPanel {

    /**
     * Creates new form UpdateCus
     */
    DBConnect dbc;
    ResultSet rs;
    String cid, mob;
    public UpdateCus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mbl = new javax.swing.JTextField();
        upBtn = new javax.swing.JButton();
        searchEID = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        updateCID = new javax.swing.JTextField();
        deleteMob = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();

        setBackground(new java.awt.Color(252, 233, 192));

        jLabel1.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel1.setText("Name :");

        name.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel3.setText("Mobile : ");

        mbl.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        upBtn.setBackground(new java.awt.Color(153, 255, 255));
        upBtn.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N
        upBtn.setText("Update");
        upBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upBtnActionPerformed(evt);
            }
        });

        searchEID.setBackground(new java.awt.Color(204, 255, 204));
        searchEID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        searchEID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEIDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel2.setText("Customer ID: ");

        updateCID.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        deleteMob.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel4.setText("Mobile");

        jLabel5.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        jLabel5.setText("Email : ");

        email.setFont(new java.awt.Font("Californian FB", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateCID, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteMob, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(searchEID)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(upBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mbl, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(192, 192, 192)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)))
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchEID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteMob))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateCID))))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(upBtn)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void upBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upBtnActionPerformed
        // TODO add your handling code here:
        
        String addName = name.getText();
        String addMbl = mbl.getText();
        String addEmail = email.getText();
        
        if(addName.isEmpty() || addMbl.isEmpty() || addEmail.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please fill up all the fields!");
        }
        
        else{
            try{
                dbc = new DBConnect();
                dbc.connectToDB();
                boolean qr = dbc.ToDB("Update Customer "
                          +"set name='"+addName+"', mobile = '"+addMbl+"', email ='"+addEmail+"' where Customer_id = "+cid);
                if(qr)
                {
                    name.setText("");
                    mbl.setText("");
                    email.setText("");

                    JOptionPane.showMessageDialog(null, "Update succesfull!");
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Error in updating");

                }
            }catch(Exception e){

            }
        }
        
    }//GEN-LAST:event_upBtnActionPerformed

    private void searchEIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEIDActionPerformed
        // TODO add your handling code here:
        
        cid = updateCID.getText();
        mob = deleteMob.getText();
        try{
            dbc = new DBConnect();
            dbc.connectToDB();
            
            if( !cid.isEmpty())
            {
                deleteMob.setText("");
                rs = dbc.queryToDB("select * from Customer where customer_id = "+cid);
                if(!rs.next())
                {
                    name.setText("");
                    mbl.setText("");
                    email.setText("");
                    JOptionPane.showMessageDialog(null, "No customer found with Customer ID : "+cid);     
                }
                else
                {
                    do{
                        cid = String.valueOf(rs.getInt("customer_id"));
                        String UPname = rs.getString("name");
                        String UPmblNo = rs.getString("mobile");
                        String UPvs = rs.getString("email");
                        //String UPpoints = String.valueOf(rs.getInt("Points"));

                        name.setText(UPname);
                        mbl.setText(UPmblNo);
                        email.setText(UPvs);
                    }while(rs.next());
                }
            }
            else if( !mob.isEmpty() )
            {
                rs = dbc.queryToDB("select * from Customer where mobile = "+mob);
                if(!rs.next())
                {
                    name.setText("");
                    mbl.setText("");
                    email.setText("");
                    JOptionPane.showMessageDialog(null, "No customer found with mobile : "+mob);     
                }
                else
                {
                    do{
                        cid = String.valueOf(rs.getInt("customer_id"));
                        String UPname = rs.getString("name");
                        String UPmblNo = rs.getString("mobile");
                        String UPvs = rs.getString("email");
                        //String UPpoints = String.valueOf(rs.getInt("Points"));

                        name.setText(UPname);
                        mbl.setText(UPmblNo);
                        email.setText(UPvs);
                    }while(rs.next());
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Please enter Customer ID or Mobile");     
            }

            

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_searchEIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField deleteMob;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField mbl;
    private javax.swing.JTextField name;
    private javax.swing.JButton searchEID;
    private javax.swing.JButton upBtn;
    private javax.swing.JTextField updateCID;
    // End of variables declaration//GEN-END:variables
}
